### rechercher tout les évenements
GET http://localhost:3000/evenements

### rechercher un évenement avec son id
GET http://localhost:3000/evenements/2

### nouvel evenment
POST http://localhost:3000/evenements
content-type: application/json

{
    "tag_id": "1",
    "animal_id": "1",
    "title": "dents de sagesse",
    "description": "les chiens ont des dents de sagesse?",
    "date": "2022-04-01 16:00:00"
}

### modifier un evenment
PATCH http://localhost:3000/evenements/10
content-type: application/json

{
    "tag_id": "2",
    "animal_id": "5",
    "title": "antipuce",
    "description": "1 pipette",
    "date": "2022-04-01 16:00:00"
}


### supprimer un evenement
DELETE http://localhost:3000/evenements/10
