
### rechercher tout les profils
GET http://localhost:3000/profils

### rechercher un profil avec son id
GET http://localhost:3000/profils/2


### inscription
POST http://localhost:3000/profils/inscription
content-type: application/json

{
    "lastname": "valjean",
    "firstname": "jean",
    "email": "jeanjean8@gmail.com",
    "password": "jeanjean",
    "confirmPassword": "jeanjean"
}


### connexion
POST http://localhost:3000/profils/connexion
content-type: application/json

{
    "email": "jeanjean5@gmail.com",
    "password": "jeanjean"
}


### modifier d'un profil
PATCH http://localhost:3000/profils/4
content-type: application/json

{
    "lastname": "valjean",
    "firstname": "jean",
    "email": "jeanjean@gmail.com",
    "password": "jeanjean",
    "confirmPassword": "jeanjean"
}


### supprimer un profil avec son id
DELETE http://localhost:3000/profils/4

